### ISSUE TITLE
aheatmap clusters differently from version 0.20.6 to 0.21.0

### ISSUE THREAD

**Issue by AmyOlex** [renozao/NMF#117]
Hello,

I just recently updated my NMF package to 0.21.0 from 0.20.6.  When I run the same script using ward linkage on the same data I get a different clustering solution.  I am unable to reproduce some heatmaps I need for a manuscript.  A colleague still has the older version and when running the same script on the same data we get 2 different heatmaps!  Is there a way to downgrade back to 0.20.6 so I can at least get reproducible figures?  Also, why is the clustering different?  I'm using "correlation" with "ward" linkage.  Thank You!

**Comment by renozao** [comment]
There was an issue in the computation of the correlation distance, which was fixed in 286e25b, This fix is included in the current CRAN version 0.21. 

The computation in version 0.20.6 was not correct because it used the euclidean distance on the correlation matrix (`1 - cor(x)`) instead of using it directly as a distance/dissimilarity metric.

If need be you should be able to downgrade to 0.20.6 from CRAN archive:
```R
devtools::install_version("NMF", "0.20.6")
```
